Repository open-rpc/open-rpc, pull requests merged in 2019-05, with the labels that each got.

#8 fix: add missing repos
  README.md
Labels: enhancement

#10 fix: remove console log
  docs/.vuepress/theme/Layout.vue
Labels: bug

#11 Fix/link typo
  docs/beginners/index.md
Labels: bug

#14 feat: builds to s3 on circle
  .circleci/config.yml
  .releaserc
  package-lock.json
  package.json
Labels: enhancement

#16 feat: invalidate cloudfront cache
  .circleci/config.yml
Labels: bug, enhancement

#15 fix: remove whitespace
  README.md
Labels: bug

#17 fix: s3 deploy fixup
  .circleci/config.yml
Labels: bug

#18 fix: cloudfront invalidation broken
  .circleci/config.yml
Labels: bug

#19 fix: path incorrect
  .circleci/config.yml
Labels: bug

#20 fix: last try before I give up
  .circleci/config.yml
Labels: bug

#22 fix: add vscode
  docs/developers/index.md
Labels: enhancement

#25 feat: add discord widget
  docs/.vuepress/config.js
Labels: enhancement

#27 fix: add directory links to spec + playground + discord
  docs/.vuepress/theme/components/Footer.vue
Labels: enhancement

#29 fix(README): windows instructions
  README.md
Labels: bug
